# Site settings
title: lucisferre
email: chnicola@gmail.com
description: "Software, startups and relentless improvement."
baseurl: ""
url: "http://lucisferre.net"

# Build settings
markdown: redcarpet
permalink: pretty

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: css
  style: :compressed
