# Site settings
title: lucisferre
email: chnicola@gmail.com
description: "Thoughts on software, startups and relentless improvement."
baseurl: ""

# Build settings
markdown: redcarpet
permalink: /:year/:month/:day/:title/
highlighter: pygments

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: css
  style: :compressed
